"""Initial migration.

Revision ID: d13fd487b0db
Revises: 
Create Date: 2025-04-17 21:39:33.312661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13fd487b0db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('reference_image_path', sa.String(length=256), nullable=False),
    sa.Column('_face_encoding', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_image_path')
    )
    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardian_name'), ['name'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('teacher_email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_teacher_email'), ['teacher_email'], unique=False)

    op.create_table('guardian_student',
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('guardian_id', 'student_id')
    )
    op.create_table('pickup_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('verified_image_path', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pickup_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_log_timestamp'))

    op.drop_table('pickup_log')
    op.drop_table('guardian_student')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_teacher_email'))
        batch_op.drop_index(batch_op.f('ix_student_name'))

    op.drop_table('student')
    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardian_name'))

    op.drop_table('guardian')
    # ### end Alembic commands ###
